
addons:
  browserstack:
    username: "harrysarson1"
    access_key:
      secure: "YYIZb5kfKT9AIcusLMmM8jbXiQNA8KCi3giRPMrlk9Nt3lScmQfVYGI9jsm8/YW4I5K8XLSddxfmFPSAfCLvMPW4Mglye27nVv5r8N7Gt1IkdxXlRt8Uj+hgZ+HhEwJEX/ddyBk7S4hF8eej0Az718pC1lyCXxu57MKFvU24zWk="

language: node_js
node_js:
  - 6
  - 8
  - 10

jobs:
  include:
    - stage: browser-tests
      node_js: 8
      script: npm run test:browser
    - stage: browserstack
      node_js: 8
      script: npm run test:browserstack
